# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Docker Build

on:
  push:
    branches: [ "main", "314-from-312-debug-jax-version-gpu-compat" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # REMOVED: actions/setup-python. It is redundant because the build and test run inside Docker,
    # which has its own Python environment defined in the Dockerfile.

    - name: Build Docker Image
      run: docker build -t davidt101/cerebros-llm:${{ github.run_number }} .

    - name: Run Smoke Test
      run: |
        docker run -t \
          -v $(pwd)/artifacts:/opt/artifacts \
          -e MLFLOW_PORT=7777 \
          -e DATASET_TO_RUN="david-thrower/tiny-stories-mini-96-seq-len-50000-samples" \
          -e PHASE_I_A_SAMPLES_TO_CREATE=2 \
          -e PHASE_I_B_SAMPLES_TO_CREATE=4 \
          -e PHASE_I_B_SAMPLE_EXPANSION_BATCH_SIZE=2 \
          -e PHASE_I_B_VAL_SPLIT=0.15 \
          -e MAX_SEQ_LENGTH=96 \
          davidt101/cerebros-llm:${{ github.run_number }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      # if: ${{ github.ref_name == '312-from-311-add-automated-dockerhub-push-of-container' }}
      run: |
        docker tag davidt101/cerebros-llm:${{ github.run_number }} davidt101/cerebros-llm:latest
        docker push davidt101/cerebros-llm:${{ github.run_number }}
        docker push davidt101/cerebros-llm:testgpu
